export var GeneralErrors;
(function (GeneralErrors) {
  GeneralErrors["UNHANDLED_ERROR"] = "UNHANDLED_ERROR";
  GeneralErrors["URL_CANT_BE_LOADED"] = "URL_CANT_BE_LOADED";
  GeneralErrors["CAMPAIGN_NOT_AUTHORIZED"] = "CAMPAIGN_NOT_AUTHORIZED";
  GeneralErrors["TEMPLATE_PREVIEW_NOT_FOUND"] = "TEMPLATE_PREVIEW_NOT_FOUND";
})(GeneralErrors || (GeneralErrors = {}));
export var UserErrors;
(function (UserErrors) {
  UserErrors["ERROR_WHILE_CREATING_USER_IN_LDAP"] =
    "ERROR_WHILE_CREATING_USER_IN_LDAP";
  UserErrors["ERROR_WHILE_VALIDATING_USER"] = "ERROR_WHILE_VALIDATING_USER";
  UserErrors["ERROR_WHILE_SETUP_NEW_PASSWORD"] =
    "ERROR_WHILE_SETUP_NEW_PASSWORD";
  UserErrors["ERROR_WHILE_VALIDATING_NEW_PASSWORD"] =
    "ERROR_WHILE_VALIDATING_NEW_PASSWORD";
  UserErrors["ERROR_WHILE_UPDATING_NEW_PASSWORD"] =
    "ERROR_WHILE_UPDATING_NEW_PASSWORD";
  UserErrors["ERROR_WHILE_SETUP_DELETE_USER"] = "ERROR_WHILE_SETUP_DELETE_USER";
  UserErrors["ERROR_WHILE_SETUP_DISABLE_USER"] =
    "ERROR_WHILE_SETUP_DISABLE_USER";
  UserErrors["ERROR_WHILE_SETUP_ENABLE_USER"] = "ERROR_WHILE_SETUP_ENABLE_USER";
  UserErrors["SEARCH_NO_ITEM_WAS_FOUND"] = "SEARCH_NO_ITEM_WAS_FOUND";
  UserErrors["ERR_INVALID_ARG_TYPE"] = "ERR_INVALID_ARG_TYPE";
  UserErrors["ERROR_WHILE_ADDING_USER_MEMBER"] =
    "ERROR_WHILE_ADDING_USER_MEMBER";
  UserErrors["ERROR_WHILE_SEARCHING_USER_IN_DATABASE"] =
    "ERROR_WHILE_SEARCHING_USER_IN_DATABASE";
})(UserErrors || (UserErrors = {}));
export var DistributionErrors;
(function (DistributionErrors) {
  DistributionErrors["ERR_INVALID_ARG_TYPE"] = "ERR_INVALID_ARG_TYPE";
  DistributionErrors["ERROR_WHILE_DELETE_ALL_DISTRIBUTIONS_LDAP"] =
    "ERROR_WHILE_DELETE_ALL_DISTRIBUTIONS_LDAP";
  DistributionErrors["ERROR_WHILE_SETUP_DELETE_DISTRIBUTION"] =
    "ERROR_WHILE_SETUP_DELETE_DISTRIBUTION";
  DistributionErrors["ERROR_WHILE_DELETE_ONE_DISTRIBUTION_LDAP"] =
    "ERROR_WHILE_DELETE_ONE_DISTRIBUTION_LDAP";
  DistributionErrors["SEARCH_NO_ITEM_WAS_FOUND"] = "SEARCH_NO_ITEM_WAS_FOUND";
})(DistributionErrors || (DistributionErrors = {}));
export var GroupErrors;
(function (GroupErrors) {
  GroupErrors["ERR_INVALID_ARG_TYPE"] = "ERR_INVALID_ARG_TYPE";
  GroupErrors["ERROR_WHILE_DELETE_ALL_GROUPS_LDAP"] =
    "ERROR_WHILE_DELETE_ALL_GROUPS_LDAP";
  GroupErrors["ERROR_WHILE_SETUP_DELETE_GROUP"] =
    "ERROR_WHILE_SETUP_DELETE_GROUP";
  GroupErrors["ERROR_WHILE_DELETE_ONE_GROUP_LDAP"] =
    "ERROR_WHILE_DELETE_ONE_GROUP_LDAP";
  GroupErrors["SEARCH_NO_ITEM_WAS_FOUND"] = "SEARCH_NO_ITEM_WAS_FOUND";
})(GroupErrors || (GroupErrors = {}));
export var ResourceErrors;
(function (ResourceErrors) {
  ResourceErrors["ERR_INVALID_ARG_TYPE"] = "ERR_INVALID_ARG_TYPE";
  ResourceErrors["ERROR_WHILE_DELETE_ONE_RESOURCE_LDAP"] =
    "ERROR_WHILE_DELETE_ONE_RESOURCE_LDAP";
  ResourceErrors["ERROR_WHILE_SETUP_EDIT_RESOURCE"] =
    "ERROR_WHILE_SETUP_EDIT_RESOURCE";
  ResourceErrors["ERROR_WHILE_VALIDATING_DATA"] = "ERROR_WHILE_VALIDATING_DATA";
  ResourceErrors["ERROR_WHILE_SETUP_DELETE_RESOURCES"] =
    "ERROR_WHILE_SETUP_DELETE_RESOURCES";
  ResourceErrors["ERROR_WHILE_CREATING_RESOURCE_IN_LDAP"] =
    "ERROR_WHILE_CREATING_RESOURCE_IN_LDAP";
  ResourceErrors["ERROR_WHILE_VALIDATING_RESOURCE"] =
    "ERROR_WHILE_VALIDATING_RESOURCE";
  ResourceErrors["ERROR_WHILE_UPDATING_RESOURCE"] =
    "ERROR_WHILE_UPDATING_RESOURCE";
})(ResourceErrors || (ResourceErrors = {}));
export var AuthenticationErrors;
(function (AuthenticationErrors) {
  AuthenticationErrors["AUTH_TOKEN_EXPIRED"] = "AUTH_TOKEN_EXPIRED";
  AuthenticationErrors["AUTH_MUST_BE_LOGGED_OFF"] = "AUTH_MUST_BE_LOGGED_OFF";
  AuthenticationErrors["AUTH_NO_TOKEN_PROVIDED"] = "AUTH_NO_TOKEN_PROVIDED";
  AuthenticationErrors["AUTH_TOKEN_IS_NOT_AUTHENTIC"] =
    "AUTH_TOKEN_IS_NOT_AUTHENTIC";
  AuthenticationErrors["AUTH_INVALID_CREDENTIALS"] = "AUTH_INVALID_CREDENTIALS";
  AuthenticationErrors["AUTH_NO_ROLE_ALLOWED"] = "AUTH_NO_ROLE_ALLOWED";
  AuthenticationErrors["AUTH_ACCESS_TO_INTRANET_NOT_ALLOWED"] =
    "AUTH_ACCESS_TO_INTRANET_NOT_ALLOWED";
  AuthenticationErrors["AUTH_DISABLED_ACCOUNT"] = "AUTH_DISABLED_ACCOUNT";
  AuthenticationErrors["ACCESS_NOT_AUTHORIZED"] = "ACCESS_NOT_AUTHORIZED";
})(AuthenticationErrors || (AuthenticationErrors = {}));
//# sourceMappingURL=BackendErrors.js.map
