export enum GeneralErrors {
  UNHANDLED_ERROR = "UNHANDLED_ERROR",
  URL_CANT_BE_LOADED = "URL_CANT_BE_LOADED",
  CAMPAIGN_NOT_AUTHORIZED = "CAMPAIGN_NOT_AUTHORIZED",
  TEMPLATE_PREVIEW_NOT_FOUND = "TEMPLATE_PREVIEW_NOT_FOUND",
}

export enum UserErrors {
  ERROR_WHILE_CREATING_USER_IN_LDAP = "ERROR_WHILE_CREATING_USER_IN_LDAP",
  ERROR_WHILE_VALIDATING_USER = "ERROR_WHILE_VALIDATING_USER",
  ERROR_WHILE_SETUP_NEW_PASSWORD = "ERROR_WHILE_SETUP_NEW_PASSWORD",
  ERROR_WHILE_VALIDATING_NEW_PASSWORD = "ERROR_WHILE_VALIDATING_NEW_PASSWORD",
  ERROR_WHILE_UPDATING_NEW_PASSWORD = "ERROR_WHILE_UPDATING_NEW_PASSWORD",
  ERROR_WHILE_SETUP_DELETE_USER = "ERROR_WHILE_SETUP_DELETE_USER",
  ERROR_WHILE_SETUP_DISABLE_USER = "ERROR_WHILE_SETUP_DISABLE_USER",
  ERROR_WHILE_SETUP_ENABLE_USER = "ERROR_WHILE_SETUP_ENABLE_USER",
  SEARCH_NO_ITEM_WAS_FOUND = "SEARCH_NO_ITEM_WAS_FOUND",
  ERR_INVALID_ARG_TYPE = "ERR_INVALID_ARG_TYPE",
  ERROR_WHILE_ADDING_USER_MEMBER = "ERROR_WHILE_ADDING_USER_MEMBER",
  ERROR_WHILE_SEARCHING_USER_IN_DATABASE = "ERROR_WHILE_SEARCHING_USER_IN_DATABASE",
}

export enum DistributionErrors {
  ERR_INVALID_ARG_TYPE = "ERR_INVALID_ARG_TYPE",
  ERROR_WHILE_DELETE_ALL_DISTRIBUTIONS_LDAP = "ERROR_WHILE_DELETE_ALL_DISTRIBUTIONS_LDAP",
  ERROR_WHILE_SETUP_DELETE_DISTRIBUTION = "ERROR_WHILE_SETUP_DELETE_DISTRIBUTION",
  ERROR_WHILE_DELETE_ONE_DISTRIBUTION_LDAP = "ERROR_WHILE_DELETE_ONE_DISTRIBUTION_LDAP",
  SEARCH_NO_ITEM_WAS_FOUND = "SEARCH_NO_ITEM_WAS_FOUND",
}

export enum GroupErrors {
  ERR_INVALID_ARG_TYPE = "ERR_INVALID_ARG_TYPE",
  ERROR_WHILE_DELETE_ALL_GROUPS_LDAP = "ERROR_WHILE_DELETE_ALL_GROUPS_LDAP",
  ERROR_WHILE_SETUP_DELETE_GROUP = "ERROR_WHILE_SETUP_DELETE_GROUP",
  ERROR_WHILE_DELETE_ONE_GROUP_LDAP = "ERROR_WHILE_DELETE_ONE_GROUP_LDAP",
  SEARCH_NO_ITEM_WAS_FOUND = "SEARCH_NO_ITEM_WAS_FOUND",
}

export enum ResourceErrors {
  ERR_INVALID_ARG_TYPE = "ERR_INVALID_ARG_TYPE",
  ERROR_WHILE_DELETE_ONE_RESOURCE_LDAP = "ERROR_WHILE_DELETE_ONE_RESOURCE_LDAP",
  ERROR_WHILE_SETUP_EDIT_RESOURCE = "ERROR_WHILE_SETUP_EDIT_RESOURCE",
  ERROR_WHILE_VALIDATING_DATA = "ERROR_WHILE_VALIDATING_DATA",
  ERROR_WHILE_SETUP_DELETE_RESOURCES = "ERROR_WHILE_SETUP_DELETE_RESOURCES",
  ERROR_WHILE_CREATING_RESOURCE_IN_LDAP = "ERROR_WHILE_CREATING_RESOURCE_IN_LDAP",
  ERROR_WHILE_VALIDATING_RESOURCE = "ERROR_WHILE_VALIDATING_RESOURCE",
  ERROR_WHILE_UPDATING_RESOURCE = "ERROR_WHILE_UPDATING_RESOURCE",
}

export enum AuthenticationErrors {
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  AUTH_MUST_BE_LOGGED_OFF = "AUTH_MUST_BE_LOGGED_OFF",
  AUTH_NO_TOKEN_PROVIDED = "AUTH_NO_TOKEN_PROVIDED",
  AUTH_TOKEN_IS_NOT_AUTHENTIC = "AUTH_TOKEN_IS_NOT_AUTHENTIC",
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_NO_ROLE_ALLOWED = "AUTH_NO_ROLE_ALLOWED",
  AUTH_ACCESS_TO_INTRANET_NOT_ALLOWED = "AUTH_ACCESS_TO_INTRANET_NOT_ALLOWED",
  AUTH_DISABLED_ACCOUNT = "AUTH_DISABLED_ACCOUNT",
  ACCESS_NOT_AUTHORIZED = "ACCESS_NOT_AUTHORIZED",
}
